integer ::= INT;
id ::= IDENT;

;; expressions
assignment ::= term (ASSIGN term)?;
term ::= factor ((PLUS | MINUS) factor)*;
factor ::= atom ((TIMES | DIVIDE) atom)*;
atom ::= LPAREN expr RPAREN | integer | id | (PLUS | MINUS) expr;

expr ::= assignment;

;; statements
compound ::= statement*;
statement ::= expr SEMI;
